services:
  flutter-builder:
    build: .
    container_name: flutter_mobile_builder
    volumes:
      - .:/app
      - flutter_pub_cache:/root/.pub-cache
    networks:
      - bookworm_network
    # The built APK will be in build/app/outputs/flutter-apk/

  #Inclusion de nginx
  nginx:
    image: nginx:latest
    container_name: bookworm_nginx_mobile
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flutter-builder
    networks:
      - bookworm_network


volumes:
  flutter_pub_cache:

networks:
  bookworm_network:
    external: true
    name: bookworm_network
