services:
  flutter-builder:
    build: .
    container_name: flutter_mobile_builder
    volumes:
      - .:/app
      - flutter_pub_cache:/root/.pub-cache
    # No necesita redes - solo compila el APK

  #Inclusion de nginx
  nginx:
    image: nginx:latest
    container_name: bookworm_nginx_mobile
    ports:
      - "8081:80"  # Exponer si quieres servir la web version
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flutter-builder


volumes:
  flutter_pub_cache:
